name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: Ubuntu-18.04
    steps:
    - task: TerraformInstaller@0
      displayName: 'Terraform install'
      inputs:
        terraformVersion: 'latest'
    - task: DownloadSecureFile@1
      displayName: "Download secure file"
      name: mySSH
      inputs:
        secureFile: 'id_rsa.pub'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p ~/.ssh
          cp $(mySSH.secureFilePath)  ~/.ssh
  # Needed for Terraform VM deployment
#    - task: InstallSSHKey@0
#      inputs:
#        knownHostsEntry: 'KNOWN_HOSTS_STRING'
#        sshPublicKey: 'PUBLIC_KEY'
#        sshKeySecureFile: 'id_rsa'
    - task: TerraformTaskV2@2
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        command: 'init'
        backendServiceArm: 'Azure subscription 1(4d999104-b7c3-451d-b8d4-3d38b64ef19c)'
        backendAzureRmResourceGroupName: 'tfstate'
        backendAzureRmStorageAccountName: 'tfstate17655'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'EuwEzS0FZoFSE+RUceuoxqE1Vq2m8MohDCVYfO5YZTBb8sFyWs4Ze2LYpSWZB0aLv5R7HHaZHzLL1qQxBt9QKg=='
    - task: TerraformTaskV2@2
      displayName: 'Terraform validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
    - task: TerraformTaskV2@2
      displayName: 'Terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'terraform_conn'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    - task: TerraformTaskV2@2
      displayName: 'Terraform apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'Azure subscription 1(4d999104-b7c3-451d-b8d4-3d38b64ef19c)'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    - task: Bash@3
      displayName: 'Install Newman dependencies'
      inputs:
        targetType: 'inline'
        script: |
          sudo npm install -g newman
          sudo npm install -g newman-reporter-junitfull
    - task: Bash@3
      displayName: 'Run regression tests'
      inputs:
        targetType: 'inline'
        script: 'newman run "$(System.DefaultWorkingDirectory)/automatedtesting/postman/Regression_Tests_Postman.postman_collection.json" -e "$(System.DefaultWorkingDirectory)/automatedtesting/postman/project_3_postman.postman_environment.json" -r cli,junitfull --reporter-junitfull-export $(System.DefaultWorkingDirectory)/automatedtesting/postman/result-regression-test.xml'
    - task: Bash@3
      displayName: 'Run data validation tests'
      inputs:
        targetType: 'inline'
        script: 'newman run "$(System.DefaultWorkingDirectory)/automatedtesting/postman/Data_Validation_Tests_Postman.postman_collection.json" -e "$(System.DefaultWorkingDirectory)/automatedtesting/postman/project_3_postman.postman_environment.json" -r cli,junitfull --reporter-junitfull-export $(System.DefaultWorkingDirectory)/automatedtesting/postman/result-data-validation-test.xml'
    - task: Bash@3
      displayName: 'Devbug'
      inputs:
        targetType: 'inline'
        script: 'ls -la automatedtesting/postman'
    - task: PublishTestResults@2
      displayName: 'Post Postman regression and data validation tests'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*test.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'Regression and data validation graphs'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'path/to/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-18.04'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'Azure subscription 1(4d999104-b7c3-451d-b8d4-3d38b64ef19c)'
              appName: 'myApplicationProject3-AppService'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


